blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/maralcbr/omarchy-mx-mac/discussions
    about: Suggest a new feature, change to existing feature, or other ideas in Discussions.
  - name: Support
    url: https://github.com/maralcbr/omarchy-mx-mac/discussions
    about: Need help? Use Discussions for support. GitHub issues should be used for verified bugs only.
